//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int IdPerson { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
        public int IdGender { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
